apiVersion: v1
kind: Secret
metadata:
  name: flask-notes-db   # MUST match job + deployment
type: Opaque
stringData:
  DB_HOST: "flask-notes-mysql.cy3g00wiie5h.us-east-1.rds.amazonaws.com"
  DB_PORT: "3306"
  DB_NAME: "haridb"
  DB_USER: "hariadmin"
  DB_PASSWORD: "hari2415"
